# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Smokes Let's Go"
email: mark.monteiro23@gmail.com
description: So ya wanna smoke a dart bud?
url: "http://smokesletsgo.com" # the base hostname & protocol for your site
github-username: "mark-monteiro"

# Github Unmodifiable Settings
safe: true
lsi: false
source: .

# Github Defaults
highlighter: pygments
#github: [Repository metadata]
